version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://guest:guest@rabbitmq:5672//
    ports:
      - "8888:8000"
    tty: true
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    restart: always
    hostname: cagescan
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" 
